version: "3"
services:
  mysqldb:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=bookingDB"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=verysecret"
      - "MYSQL_USER=myuser"
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  discovery-service:
    build: ./discovery-service
    networks:
      - microservices-network
    depends_on:
      - mysqldb
    ports:
      - 9001:9001
  api-gateway:
    build: ./api-gateway
    depends_on:
      - mysqldb
      - booking-ms
      - payment
      - discovery-service
    networks:
      - microservices-network
    ports:
      - 8080:8080
  booking-ms:
    build: ./booking-ms
    networks:
      - microservices-network
    depends_on:
      - mysqldb
      - discovery-service
    ports:
      - 8081:8081
  payment:
    build: ./payment
    networks:
      - microservices-network
    depends_on:
      - mysqldb
      - discovery-service
    ports:
      - 8083:8083
networks:
  microservices-network:
